add_newline = true
command_timeout = 800
format = "$directory$git_branch$git_status$nodejs$golang$c$rust$python$cmd_duration$line_break$character"

[directory]
truncate_to_repo = true
truncation_length = 3

[git_branch]
format = "[$branch]($style) "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'

[nodejs]
format = "[node $version]($style) "

[golang]
format = "[go $version]($style) "

[c]
format = "[c]($style) "

[python]
format = "[py $version]($style) "

[cmd_duration]
min_time = 500
format = "[${duration}]($style) "

[character]
success_symbol = "[›](bold green)"
error_symbol = "[›](bold red)"
vimcmd_symbol = "[‹](bold blue)"
